# Generated by Django 3.1.7 on 2021-05-15 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210514_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(default='old_user', max_length=13),
            preserve_default=False,
        ),
    ]
