# Generated by Django 3.1.7 on 2021-05-22 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_display_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PictureProfile',
        ),
    ]
