# Generated by Django 3.1.7 on 2021-04-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0003_post_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
    ]
