# Generated by Django 3.1.7 on 2021-05-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0005_auto_20210424_2126'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
